# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FH2wmEOduIlnERHc95omyciKBtJlSCEe
"""

import pandas as pd
import os

# Create data directory and dummy dataset
os.makedirs('data', exist_ok=True)
data = {
    'Month': ['Jan', 'Jan', 'Feb', 'Feb', 'Mar', 'Mar'],
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'Sales': [1200, 800, 1500, 900, 1100, 1200]
}
pd.DataFrame(data).to_csv('data/ecommerce.csv', index=False)
print('Sample data created successfully.')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import sqlite3
# 
# # LOAD DATA
# df = pd.read_csv("data/ecommerce.csv")
# 
# # DATABASE
# conn = sqlite3.connect("database.db")
# df.to_sql("sales", conn, if_exists='replace', index=False)
# 
# # AI LOGIC
# def generate_sql(question):
#     question = question.lower()
#     if "revenue" in question:
#         return "SELECT SUM(Sales) FROM sales"
#     elif "category" in question:
#         return "SELECT Category, SUM(Sales) FROM sales GROUP BY Category"
#     elif "trend" in question:
#         return "SELECT Month, SUM(Sales) FROM sales GROUP BY Month"
#     return None
# 
# # UI
# st.title("🤖 AI Data Analyst")
# question = st.text_input("Ask a question:")
# if question:
#     query = generate_sql(question)
#     if query:
#         result = pd.read_sql_query(query, conn)
#         st.write(result)
#     else:
#         st.write("Try: total revenue, category, trend")

"""### Run the App
Execute the following cell to install requirements and start a tunnel to view your Streamlit app.
"""

!pip install -q streamlit
!npm install -q localtunnel
import subprocess
# Run streamlit in the background
subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8501'])
# Create a tunnel to provide a public URL
!npx localtunnel --port 8501