# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FH2wmEOduIlnERHc95omyciKBtJlSCEe
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score
import numpy as np

# =========================
# 🎨 CONFIG (SaaS style)
# =========================
st.set_page_config(page_title="AI Data Platform", layout="wide")

st.markdown("""
<style>
body {background-color: #0e1117; color: white;}
.stApp {background-color: #0e1117;}
h1, h2, h3 {color: white;}
</style>
""", unsafe_allow_html=True)

st.title("🚀 AI Data Platform")

# =========================
# 📂 UPLOAD
# =========================
uploaded_file = st.file_uploader("Upload CSV", type=["csv"])

if uploaded_file is None:
    st.info("Upload CSV to start")
    st.stop()

df = pd.read_csv(uploaded_file)

# =========================
# 🎛 FILTERS (sidebar)
# =========================
st.sidebar.header("Filters")

category = st.sidebar.multiselect(
    "Category",
    df["Category"].unique(),
    default=df["Category"].unique()
)

month = st.sidebar.multiselect(
    "Month",
    df["Month"].unique(),
    default=df["Month"].unique()
)

df_filtered = df[
    (df["Category"].isin(category)) &
    (df["Month"].isin(month))
]

# =========================
# 📊 KPI CARDS (SaaS feel)
# =========================
st.markdown("## 📊 Key Metrics")

col1, col2, col3 = st.columns(3)

revenue = df_filtered["Sales"].sum()
orders = len(df_filtered)
avg = round(revenue/orders, 2) if orders > 0 else 0

col1.metric("💰 Revenue", f"${revenue:,}")
col2.metric("📦 Orders", orders)
col3.metric("📊 Avg Order", f"${avg}")

# =========================
# 📊 CHARTS (Plotly)
# =========================
st.markdown("---")
st.markdown("## 📊 Analytics")

col1, col2 = st.columns(2)

# Category Chart
category_data = df_filtered.groupby("Category")["Sales"].sum().reset_index()

fig1 = px.bar(
    category_data,
    x="Category",
    y="Sales",
    color="Category",
    title="Revenue by Category"
)

with col1:
    st.plotly_chart(fig1, use_container_width=True)

# Trend Chart
trend_data = df_filtered.groupby("Month")["Sales"].sum().reset_index()

fig2 = px.line(
    trend_data,
    x="Month",
    y="Sales",
    markers=True,
    title="Sales Trend"
)

with col2:
    st.plotly_chart(fig2, use_container_width=True)

# =========================
# 🤖 AI MODELS
# =========================
st.markdown("---")
st.markdown("## 🤖 AI Forecast")

if not trend_data.empty:

    trend_data["Month_num"] = range(len(trend_data))

    X = trend_data[["Month_num"]]
    y = trend_data["Sales"]

    # Linear
    lin = LinearRegression().fit(X, y)
    lin_pred = lin.predict(X)
    r2_lin = r2_score(y, lin_pred)

    # Polynomial
    poly = PolynomialFeatures(2)
    X_poly = poly.fit_transform(X)
    poly_model = LinearRegression().fit(X_poly, y)
    poly_pred = poly_model.predict(X_poly)
    r2_poly = r2_score(y, poly_pred)

    # Compare Chart
    fig3 = px.scatter(x=X["Month_num"], y=y, labels={"x":"Time","y":"Sales"})

    fig3.add_scatter(x=X["Month_num"], y=lin_pred, mode='lines', name=f"Linear (R²={r2_lin:.2f})")
    fig3.add_scatter(x=X["Month_num"], y=poly_pred, mode='lines', name=f"Poly (R²={r2_poly:.2f})")

    st.plotly_chart(fig3, use_container_width=True)

# =========================
# 💬 CHATBOT
# =========================
st.markdown("---")
st.markdown("## 💬 AI Chat")

def chatbot(q):
    q = q.lower()

    if "revenue" in q:
        return f"Revenue: ${revenue:,}"
    elif "orders" in q:
        return f"Orders: {orders}"
    elif "category" in q:
        return category_data
    else:
        return "Try: revenue, orders, category"

question = st.text_input("Ask about your data")

if question:
    st.success(chatbot(question))

# =========================
# 🎉 FOOTER
# =========================
st.markdown("---")
st.caption("Built with Python • Streamlit • Machine Learning")